import MarqueeBanner from 'components/MarqueeBanner';
import { WelcomeToast } from 'components/WelcomeToast';
import { CartProvider } from 'components/cart/cart-context';
import { Navbar } from 'components/layout/navbar';
import { getCart } from 'lib/shopify';
import { baseUrl } from 'lib/utils';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { ReactNode } from 'react';
import { Toaster } from 'sonner';
import './globals.css';

const assistant = localFont({
  src: '../fonts/Assistant-Regular.ttf',
  variable: '--font-assistant',
});

const carattere = localFont({
  src: '../fonts/Carattere-Regular.ttf',
  variable: '--font-carattere',
});

const { SITE_NAME } = process.env;

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: {
    default: SITE_NAME!,
    template: `%s | ${SITE_NAME}`
  },
  robots: {
    follow: true,
    index: true
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children
}: {
  children: ReactNode;
}) {
  // Don't await the fetch, pass the Promise to the context provider
  const cart = getCart();

  return (
    <html lang="en" className={`${assistant.variable} ${carattere.variable}`}>
      <body className="bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white font-carattere">
        <CartProvider cartPromise={cart}>
          <MarqueeBanner />
          <Navbar />
          <main>
            {children}
            <Toaster closeButton />
            <WelcomeToast />
          </main>
        </CartProvider>
      </body>
    </html>
  );
}
